name: cts
channels:
- defaults
- conda-forge
dependencies:
- python=3.5.4
- astropy
- fysom
- ipython
- logging
- matplotlib
- numpy
- pytest
- subprocess
- tqdm
- pyvisa
- yaml


- pip:
  - sphinx-automodapi
  - opcua
  - python-can