name: cts

channels:
- defaults
- conda-forge
- auto

dependencies:
- python=3.5.4
- astropy
- fysom
- ipython
- logging
- matplotlib
- numpy
- pytest
- tqdm
- pyvisa
- yaml

- pip:
  - sphinx-automodapi
  - opcua
  - python-can