name: digicampipe
channels:
- defaults
dependencies:
- python=3.5.4
- astropy
- fysom
- ipython
- logging
- matplotlib
- numpy
- opcua
- python-can
- threading
- socket
- subprocess
- queue
- yaml


- pip:
  - sphinx-automodapi
  - python-can
